# config.yml
radio-format: '&3[&4%FREQ.%CODE&f%SUFFIX&a]&e%SENDER&7: %MESSAGE'
broadcast-format: '&2[&6%LINKID&2]&e%SENDER&f: %MESSAGE'
radio-suffix: rHz
chat-distance: 32.0
radio-distance: 96.0
chat-limited: true
radio-limited: true
enable-skywave: false
skywave-mod: 2.0
radio-min: 32
radio-max: 512
radio-cutoff-max: 15
radio-code-max: 999
radio-default-channel: 64
radio-auto-on: true
radio-item-id: 345
radio-item-required: false
antenna-range-mod: 10.0
antenna-user-mod-iron: 1
antenna-user-mod-gold: 3
antenna-user-mod-diamond: 7
antenna-tick-rate: 20
save-interval: 600000