name: AMChat
author: Xyberviri
main: com.xyberviri.amchat.AMChat
version: 0.2
description: Radio based communication
commands:
   am:
      description: display information about your radio
      permission: amchat.radio.personal.use
      usage: type /help am for more information.
   am radio:
      description: toggles your radio on off 
      permission: amchat.radio.personal.radio
      usage: Usage /am radio
   am mic:
      description: toggles your mic on off
      permission: amchat.radio.personal.mic
      usage: Usage /am mic
   am filter:
      description: toggles your filter on off
      permission: amchat.radio.personal.filter
      usage: Usage /am filter      
   am tune:
      description: Tunes personal radio to a specific channel
      permission: amchat.radio.personal.tune
      usage: Usage /am tune #
   am code:
      description: Sets the encryption code before transmission 0 to disable
      permission: amchat.radio.personal.code
      usage: Usage /am code #
   am cutoff:
      description: adjust your cutoff
      permission: amchat.radio.personal.cutoff
      usage: Usage /am cutoff #
   am home:
      description: Reset your radio to the default
      permission: amchat.radio.personal.home
      usage: Usage /am home
   am ping:
      description: send your info to another player
      permission: amchat.radio.personal.ping
      usage: Usage /am ping playername
   am list:
      description: lists all of the players online with active radios and what they are set to.
      permission: amchat.radio.list.personal
      usage: Usage /am list
   xm:
      description: display information about your fixed radio towers
      permission: amchat.radio.fixed.use
      usage: Usage /xm
      
permissions:
  amchat.*:
    description: Gives access to all am chat commands
    children:
      amchat.local.hearall: true
      amchat.radio.list.personal: true
      amchat.radio.hearall: true
      amchat.radio.readall: true
      amchat.radio.override.tune: true
      amchat.radio.override.code: true
      amchat.radio.override.cutoff: true
      amchat.radio.personal.radio: true
      amchat.radio.personal.mic: true
      amchat.radio.personal.filter: true
      amchat.radio.personal.tune: true
      amchat.radio.personal.code: true
      amchat.radio.personal.cutoff: true
      amchat.radio.personal.home: true
      amchat.radio.personal.ping: true
  amchat.radio.personal.*:
    description: Gives access to all radio commands
    default: true
    children:
      amchat.radio.personal.radio: true
      amchat.radio.personal.mic: true
      amchat.radio.personal.filter: true
      amchat.radio.personal.tune: true
      amchat.radio.personal.code: true
      amchat.radio.personal.cutoff: true
      amchat.radio.personal.home: true
      amchat.radio.personal.ping: true
  amchat.radio.override.*:
    description: Gives access to all override commands
    children:
      amchat.radio.override.tune: true
      amchat.radio.override.code: true
      amchat.radio.override.cutoff: true